/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_assginment.InventoryManager;

import javax.swing.JOptionPane;
import java_assginment.InventoryManager.Item;

/**
 *
 * @author Ivenn
 */
public class Add_New_Inventory extends javax.swing.JFrame {
    /**
     * Creates new form Add_New_Inventor
     */
    private Item_Management_Interface mainForm;

    public Add_New_Inventory(Item_Management_Interface aThis) {
        this.mainForm = aThis;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNewItem = new javax.swing.JLabel();
        lblItemName_Add = new javax.swing.JLabel();
        lblItem_SupplierName_Add = new javax.swing.JLabel();
        lblItemQuantityinStock_Add = new javax.swing.JLabel();
        lblItemPrice_Add = new javax.swing.JLabel();
        lblDimension_Add = new javax.swing.JLabel();
        lblItemReorderLevel_Add = new javax.swing.JLabel();
        txtItemName_Add = new javax.swing.JTextField();
        txtItem_SupplierName_Add = new javax.swing.JTextField();
        txtItemPrice_Add = new javax.swing.JTextField();
        txtItemDimension_Add = new javax.swing.JTextField();
        txtItemReorderLevel_Add = new javax.swing.JTextField();
        txtItemQuantityinStock_Add = new javax.swing.JTextField();
        btnAdd_AddItem = new javax.swing.JButton();
        btnCancel_AddItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(857, 491));

        lblNewItem.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        lblNewItem.setText("New Item");

        lblItemName_Add.setText("Item Name");

        lblItem_SupplierName_Add.setText("Supplier Name");

        lblItemQuantityinStock_Add.setText("Quantity in Stock");

        lblItemPrice_Add.setText("Price");

        lblDimension_Add.setText("Weight/Dimensions");

        lblItemReorderLevel_Add.setText("Reorder Level");

        txtItemName_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemName_AddActionPerformed(evt);
            }
        });

        btnAdd_AddItem.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnAdd_AddItem.setText("Add");
        btnAdd_AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_AddItemActionPerformed(evt);
            }
        });

        btnCancel_AddItem.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCancel_AddItem.setText("Cancel");
        btnCancel_AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel_AddItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(lblNewItem))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAdd_AddItem)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblItemName_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblItem_SupplierName_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblItemPrice_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblItemReorderLevel_Add)
                                        .addComponent(lblItemQuantityinStock_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDimension_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(51, 51, 51)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtItemName_Add)
                                        .addComponent(txtItem_SupplierName_Add)
                                        .addComponent(txtItemPrice_Add)
                                        .addComponent(txtItemDimension_Add)
                                        .addComponent(txtItemReorderLevel_Add)
                                        .addComponent(txtItemQuantityinStock_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(btnCancel_AddItem)))))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblNewItem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemName_Add)
                    .addComponent(txtItemName_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItem_SupplierName_Add)
                    .addComponent(txtItem_SupplierName_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemPrice_Add)
                    .addComponent(txtItemPrice_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDimension_Add)
                    .addComponent(txtItemDimension_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemReorderLevel_Add)
                    .addComponent(txtItemReorderLevel_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemQuantityinStock_Add)
                    .addComponent(txtItemQuantityinStock_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnAdd_AddItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel_AddItem)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtItemName_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemName_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemName_AddActionPerformed

    private void btnAdd_AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_AddItemActionPerformed
        //Get user inputs from the text fields
        String itemName = txtItemName_Add.getText();
        String supplierName = txtItem_SupplierName_Add.getText(); 
        String priceText = txtItemPrice_Add.getText();
        String dimensions = txtItemDimension_Add.getText();
        String reorderLevelText = txtItemReorderLevel_Add.getText();
        String quantityInStockText = txtItemQuantityinStock_Add.getText();

        //Make sure none are empty
        if (itemName.isEmpty() || supplierName.isEmpty() || priceText.isEmpty() || reorderLevelText.isEmpty() || quantityInStockText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Convert price, reorder level, and quantity to proper types
        double price = 0.0;
        int reorderLevel = 0, quantityInStock = 0;
        try {
            price = Double.parseDouble(priceText);  
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid price input!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            reorderLevel = Integer.parseInt(reorderLevelText); 
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid reorder level input!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            quantityInStock = Integer.parseInt(quantityInStockText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid quantity input!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Add the new item
        try {
            boolean itemAdded = Item.addItem(itemName, supplierName, price, dimensions, reorderLevel, quantityInStock);
            if (itemAdded) {
                JOptionPane.showMessageDialog(this, "Item added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                // Optionally, close the form
                mainForm.refreshItemTable();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Item already exists or could not be added!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }      
        
        mainForm.refreshItemTable();       
        this.setVisible(false);
    }//GEN-LAST:event_btnAdd_AddItemActionPerformed

    private void btnCancel_AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel_AddItemActionPerformed
        Item_Management_Interface itemManagement = new Item_Management_Interface();
        this.setVisible(false);
        mainForm.setVisible(true); 
    }//GEN-LAST:event_btnCancel_AddItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_New_Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_New_Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_New_Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_New_Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Item_Management_Interface mainForm = new Item_Management_Interface();
                new Add_New_Inventory(mainForm).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd_AddItem;
    private javax.swing.JButton btnCancel_AddItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDimension_Add;
    private javax.swing.JLabel lblItemName_Add;
    private javax.swing.JLabel lblItemPrice_Add;
    private javax.swing.JLabel lblItemQuantityinStock_Add;
    private javax.swing.JLabel lblItemReorderLevel_Add;
    private javax.swing.JLabel lblItem_SupplierName_Add;
    private javax.swing.JLabel lblNewItem;
    private javax.swing.JTextField txtItemDimension_Add;
    private javax.swing.JTextField txtItemName_Add;
    private javax.swing.JTextField txtItemPrice_Add;
    private javax.swing.JTextField txtItemQuantityinStock_Add;
    private javax.swing.JTextField txtItemReorderLevel_Add;
    private javax.swing.JTextField txtItem_SupplierName_Add;
    // End of variables declaration//GEN-END:variables
}
