/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_assginment.InventoryManager;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivenn
 */
public class Add_New_Supplier extends javax.swing.JFrame {

    /**
     * Creates new form Add_New_Supplier
     */
    private Supplier_Management_Interface mainForm;

    public Add_New_Supplier(Supplier_Management_Interface aThis) {
        this.mainForm = aThis;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNewSupplier = new javax.swing.JLabel();
        lblSupplierName_Add = new javax.swing.JLabel();
        lblSupplierContactNumber_Add = new javax.swing.JLabel();
        lblSupplierEmail_Add = new javax.swing.JLabel();
        lblSupplier_ItemIds_Add = new javax.swing.JLabel();
        lblSupplierPaymentMethod_Add = new javax.swing.JLabel();
        lblSupplierShippingMethod_Add = new javax.swing.JLabel();
        txtSupplierName_Add = new javax.swing.JTextField();
        txtSupplierContactNumber_Add = new javax.swing.JTextField();
        txtSupplierEmail_Add = new javax.swing.JTextField();
        txtSupplier_ItemIds_Add = new javax.swing.JTextField();
        txtSupplierPaymentMethod_Add = new javax.swing.JTextField();
        txtSupplierShippingMethod_Add = new javax.swing.JTextField();
        btnAdd_AddSupplier = new javax.swing.JButton();
        btnCancel_AddSupplier = new javax.swing.JButton();
        lblSupplierSupplyCapacity_Add = new javax.swing.JLabel();
        lblSupplierLeadTime_Add = new javax.swing.JLabel();
        txtSupplierSupplyCapacity_Add = new javax.swing.JTextField();
        txtSupplierLeadTime_Add = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lblNewSupplier.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        lblNewSupplier.setText("New Supplier");

        lblSupplierName_Add.setText("Supplier Name");

        lblSupplierContactNumber_Add.setText("Contact Number");

        lblSupplierEmail_Add.setText("Email");

        lblSupplier_ItemIds_Add.setText("Item IDs");

        lblSupplierPaymentMethod_Add.setText("Payment Method");

        lblSupplierShippingMethod_Add.setText("Shipping Method");

        btnAdd_AddSupplier.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnAdd_AddSupplier.setText("Add");
        btnAdd_AddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_AddSupplierActionPerformed(evt);
            }
        });

        btnCancel_AddSupplier.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCancel_AddSupplier.setText("Cancel");
        btnCancel_AddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel_AddSupplierActionPerformed(evt);
            }
        });

        lblSupplierSupplyCapacity_Add.setText("Supply Capacity");

        lblSupplierLeadTime_Add.setText("Lead Time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblSupplierName_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSupplierContactNumber_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSupplierEmail_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSupplier_ItemIds_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSupplierPaymentMethod_Add)
                                .addComponent(lblSupplierShippingMethod_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSupplierSupplyCapacity_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSupplierLeadTime_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSupplierName_Add)
                            .addComponent(txtSupplierContactNumber_Add)
                            .addComponent(txtSupplierEmail_Add)
                            .addComponent(txtSupplier_ItemIds_Add)
                            .addComponent(txtSupplierPaymentMethod_Add)
                            .addComponent(txtSupplierShippingMethod_Add)
                            .addComponent(txtSupplierSupplyCapacity_Add)
                            .addComponent(txtSupplierLeadTime_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdd_AddSupplier)
                            .addComponent(btnCancel_AddSupplier)))
                    .addComponent(lblNewSupplier))
                .addGap(326, 326, 326))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblNewSupplier)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierName_Add)
                    .addComponent(txtSupplierName_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierContactNumber_Add)
                    .addComponent(txtSupplierContactNumber_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierEmail_Add)
                    .addComponent(txtSupplierEmail_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplier_ItemIds_Add)
                    .addComponent(txtSupplier_ItemIds_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierPaymentMethod_Add)
                    .addComponent(txtSupplierPaymentMethod_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierShippingMethod_Add)
                    .addComponent(txtSupplierShippingMethod_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierSupplyCapacity_Add)
                    .addComponent(txtSupplierSupplyCapacity_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd_AddSupplier))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierLeadTime_Add)
                    .addComponent(txtSupplierLeadTime_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel_AddSupplier))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd_AddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_AddSupplierActionPerformed
    // Get user inputs from the text fields
    String supplierName = txtSupplierName_Add.getText();
    String contactNumber = txtSupplierContactNumber_Add.getText();
    String email = txtSupplierEmail_Add.getText();
    String itemIdsText = txtSupplier_ItemIds_Add.getText(); 
    List<String> itemIds = Arrays.asList(itemIdsText.split("[,;]")); 
    String paymentMethod = txtSupplierPaymentMethod_Add.getText();
    String shippingMethod = txtSupplierShippingMethod_Add.getText();
    String supplyCapacityText = txtSupplierSupplyCapacity_Add.getText();
    String leadTimeText = txtSupplierLeadTime_Add.getText();

    //Make sure none are empty
    if (supplierName.isEmpty() || contactNumber.isEmpty() || email.isEmpty() ||
        paymentMethod.isEmpty() || shippingMethod.isEmpty() || supplyCapacityText.isEmpty() || leadTimeText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required!", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    //Validation for supply capacity and lead time (still in Strings)
    int supplyCapacity = 0, leadTime = 0;
    try {
        supplyCapacity = Integer.parseInt(supplyCapacityText);  
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid supply capacity input! Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    try {
        leadTime = Integer.parseInt(leadTimeText); 
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid lead time input! Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    //Add the new supplier
    try {
        boolean supplierAdded = Supplier.addSupplier(supplierName, contactNumber, email, itemIds, paymentMethod, shippingMethod, supplyCapacityText, leadTimeText);
        if (supplierAdded) {
            JOptionPane.showMessageDialog(this, "Supplier added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

            mainForm.refreshSupplierTable();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Supplier already exists or could not be added!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "An error occurred while adding the supplier. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    mainForm.refreshSupplierTable();
    this.setVisible(false);

    }//GEN-LAST:event_btnAdd_AddSupplierActionPerformed

    private void btnCancel_AddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel_AddSupplierActionPerformed
        Supplier_Management_Interface supplierManagement = new Supplier_Management_Interface();
        this.setVisible(false);
        mainForm.setVisible(true);
    }//GEN-LAST:event_btnCancel_AddSupplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_New_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_New_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_New_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_New_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Supplier_Management_Interface mainForm = new Supplier_Management_Interface();
                new Add_New_Supplier(mainForm).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd_AddSupplier;
    private javax.swing.JButton btnCancel_AddSupplier;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNewSupplier;
    private javax.swing.JLabel lblSupplierContactNumber_Add;
    private javax.swing.JLabel lblSupplierEmail_Add;
    private javax.swing.JLabel lblSupplierLeadTime_Add;
    private javax.swing.JLabel lblSupplierName_Add;
    private javax.swing.JLabel lblSupplierPaymentMethod_Add;
    private javax.swing.JLabel lblSupplierShippingMethod_Add;
    private javax.swing.JLabel lblSupplierSupplyCapacity_Add;
    private javax.swing.JLabel lblSupplier_ItemIds_Add;
    private javax.swing.JTextField txtSupplierContactNumber_Add;
    private javax.swing.JTextField txtSupplierEmail_Add;
    private javax.swing.JTextField txtSupplierLeadTime_Add;
    private javax.swing.JTextField txtSupplierName_Add;
    private javax.swing.JTextField txtSupplierPaymentMethod_Add;
    private javax.swing.JTextField txtSupplierShippingMethod_Add;
    private javax.swing.JTextField txtSupplierSupplyCapacity_Add;
    private javax.swing.JTextField txtSupplier_ItemIds_Add;
    // End of variables declaration//GEN-END:variables
}
