/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_assginment.InventoryManager;

import javax.swing.JOptionPane;
import java.io.IOException;

/**
 *
 * @author Ivenn
 */
public class Edit_Item extends javax.swing.JFrame {
    private Item_Management_Interface mainInterface;

    public void setMainInterface(Item_Management_Interface mainInterface) {
        this.mainInterface = mainInterface;
    }
    
    private final Item selectedItem;
        
    public Edit_Item(Item selectedItem) {
        this.selectedItem = selectedItem;
        initComponents();
        populateItems();
    }
    
    private void populateItems(){
        lblItemID_Old.setText(selectedItem.getItemId());
        lblItemName_Old.setText(selectedItem.getItemName());
        lblItem_SupplierId_Old.setText(selectedItem.getSupplierId());
        lblItemPrice_Old.setText(String.valueOf(selectedItem.getPrice()));
        lblItemDimension_Old.setText(selectedItem.getDimensions());
        lblItemReorderLevel_Old.setText(String.valueOf(selectedItem.getReorderLevel()));
        lblItemQuantityinStock_Old.setText(String.valueOf(selectedItem.getQuantityInStock()));
    }
    
    
    //Method to save the updated item
    private void saveChanges() {
        if (selectedItem == null) {
            JOptionPane.showMessageDialog(this, "No item selected to edit.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean changesMade = false;

        //Validate and update item name
        String newItemName = txtItemName_Edit.getText().trim();
        if (!newItemName.isEmpty() && !newItemName.equals(selectedItem.getItemName())) {
            selectedItem.setItemName(newItemName);
            changesMade = true;
        }

        //Validate and update price
        String priceStr = txtItemPrice_Edit.getText().trim();
        if (!priceStr.isEmpty()) {
            try {
                double newPrice = Double.parseDouble(priceStr);
                if (newPrice != selectedItem.getPrice()) {
                    selectedItem.setPrice(newPrice);
                    changesMade = true;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid price format.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        //Validate and update dimensions
        String newDimensions = txtItemDimension_Edit.getText().trim();
        if (!newDimensions.isEmpty() && !newDimensions.equals(selectedItem.getDimensions())) {
            selectedItem.setDimensions(newDimensions);
            changesMade = true;
        }

        //Validate and update reorder level
        String reorderLevelStr = txtItemReorderLevel_Edit.getText().trim();
        if (!reorderLevelStr.isEmpty()) {
            try {
                int newReorderLevel = Integer.parseInt(reorderLevelStr);
                if (newReorderLevel != selectedItem.getReorderLevel()) {
                    selectedItem.setReorderLevel(newReorderLevel);
                    changesMade = true;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid reorder level format.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        //Validate and update quantity in stock
        String quantityStr = txtItemQuantityinStock_Edit.getText().trim();
        if (!quantityStr.isEmpty()) {
            try {
                int newQuantity = Integer.parseInt(quantityStr);
                if (newQuantity != selectedItem.getQuantityInStock()) {
                    selectedItem.setQuantityInStock(newQuantity);
                    changesMade = true;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid quantity format.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        if (!changesMade) {
            JOptionPane.showMessageDialog(this, "No changes were made.", "No Changes", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        Item.saveItem(selectedItem);

        JOptionPane.showMessageDialog(this, "Item updated successfully!");
        mainInterface.refreshItemTable();
        this.dispose();
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEditItem = new javax.swing.JLabel();
        lblItemID_Edit = new javax.swing.JLabel();
        lblItemName_Edit = new javax.swing.JLabel();
        lblItem_SupplierId_Edit = new javax.swing.JLabel();
        lblItemPrice_Edit = new javax.swing.JLabel();
        lblItemDimension_Edit = new javax.swing.JLabel();
        lblItemReorderLevel_Edit = new javax.swing.JLabel();
        lblItemQuantityinStock_Edit = new javax.swing.JLabel();
        txtItemQuantityinStock_Edit = new javax.swing.JTextField();
        txtItemReorderLevel_Edit = new javax.swing.JTextField();
        txtItemDimension_Edit = new javax.swing.JTextField();
        txtItemPrice_Edit = new javax.swing.JTextField();
        txtItemName_Edit = new javax.swing.JTextField();
        lblItemID_Old = new javax.swing.JLabel();
        lblItem_SupplierId_Old = new javax.swing.JLabel();
        btnSaveChanges_EditItem = new javax.swing.JButton();
        btnCancel_EditItem = new javax.swing.JButton();
        lblItemName_Old = new javax.swing.JLabel();
        lblItemPrice_Old = new javax.swing.JLabel();
        lblItemDimension_Old = new javax.swing.JLabel();
        lblItemReorderLevel_Old = new javax.swing.JLabel();
        lblItemQuantityinStock_Old = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(857, 491));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(857, 491));

        lblEditItem.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        lblEditItem.setText("Edit Item");

        lblItemID_Edit.setText("Item ID");

        lblItemName_Edit.setText("Item Name");

        lblItem_SupplierId_Edit.setText("Supplier ID");

        lblItemPrice_Edit.setText("Price");

        lblItemDimension_Edit.setText("Weight/Dimensions");

        lblItemReorderLevel_Edit.setText("Reorder Level");

        lblItemQuantityinStock_Edit.setText("Quantity in Stock");

        txtItemPrice_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemPrice_EditActionPerformed(evt);
            }
        });

        txtItemName_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemName_EditActionPerformed(evt);
            }
        });

        lblItemID_Old.setText("jLabel9");

        lblItem_SupplierId_Old.setText("jLabel10");

        btnSaveChanges_EditItem.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnSaveChanges_EditItem.setText("Save Changes");
        btnSaveChanges_EditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChanges_EditItemActionPerformed(evt);
            }
        });

        btnCancel_EditItem.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCancel_EditItem.setText("Cancel");
        btnCancel_EditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel_EditItemActionPerformed(evt);
            }
        });

        lblItemName_Old.setText("jLabel11");

        lblItemPrice_Old.setText("jLabel12");

        lblItemDimension_Old.setText("jLabel13");

        lblItemReorderLevel_Old.setText("jLabel14");

        lblItemQuantityinStock_Old.setText("jLabel15");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblItemID_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblItemName_Edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblItem_SupplierId_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblItemPrice_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblItemReorderLevel_Edit))
                    .addComponent(lblItemQuantityinStock_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItemDimension_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItemDimension_Old, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblItemName_Old, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblItemQuantityinStock_Old, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblItemPrice_Old, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblItem_SupplierId_Old, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblItemReorderLevel_Old, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblItemID_Old, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblEditItem, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtItemName_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))
                    .addComponent(txtItemDimension_Edit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtItemQuantityinStock_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnCancel_EditItem))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtItemPrice_Edit)
                            .addComponent(txtItemReorderLevel_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(btnSaveChanges_EditItem)))
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblEditItem)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemID_Edit)
                    .addComponent(lblItemID_Old))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemName_Edit)
                    .addComponent(lblItemName_Old)
                    .addComponent(txtItemName_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItem_SupplierId_Edit)
                            .addComponent(lblItem_SupplierId_Old))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItemPrice_Edit)
                            .addComponent(lblItemPrice_Old))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItemDimension_Edit)
                            .addComponent(lblItemDimension_Old)
                            .addComponent(txtItemDimension_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtItemPrice_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItemReorderLevel_Edit)
                            .addComponent(lblItemReorderLevel_Old)
                            .addComponent(txtItemReorderLevel_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaveChanges_EditItem))))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemQuantityinStock_Edit)
                    .addComponent(lblItemQuantityinStock_Old)
                    .addComponent(txtItemQuantityinStock_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel_EditItem))
                .addGap(0, 96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancel_EditItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel_EditItemActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancel_EditItemActionPerformed

    private void btnSaveChanges_EditItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChanges_EditItemActionPerformed
        saveChanges();
        mainInterface.refreshItemTable();
    }//GEN-LAST:event_btnSaveChanges_EditItemActionPerformed

    private void txtItemPrice_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemPrice_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemPrice_EditActionPerformed

    private void txtItemName_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemName_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemName_EditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Item selectedItem = getSelectedItem(); 
                new Edit_Item (selectedItem).setVisible(true);
            }

            private Item getSelectedItem() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel_EditItem;
    private javax.swing.JButton btnSaveChanges_EditItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEditItem;
    private javax.swing.JLabel lblItemDimension_Edit;
    private javax.swing.JLabel lblItemDimension_Old;
    private javax.swing.JLabel lblItemID_Edit;
    private javax.swing.JLabel lblItemID_Old;
    private javax.swing.JLabel lblItemName_Edit;
    private javax.swing.JLabel lblItemName_Old;
    private javax.swing.JLabel lblItemPrice_Edit;
    private javax.swing.JLabel lblItemPrice_Old;
    private javax.swing.JLabel lblItemQuantityinStock_Edit;
    private javax.swing.JLabel lblItemQuantityinStock_Old;
    private javax.swing.JLabel lblItemReorderLevel_Edit;
    private javax.swing.JLabel lblItemReorderLevel_Old;
    private javax.swing.JLabel lblItem_SupplierId_Edit;
    private javax.swing.JLabel lblItem_SupplierId_Old;
    private javax.swing.JTextField txtItemDimension_Edit;
    private javax.swing.JTextField txtItemName_Edit;
    private javax.swing.JTextField txtItemPrice_Edit;
    private javax.swing.JTextField txtItemQuantityinStock_Edit;
    private javax.swing.JTextField txtItemReorderLevel_Edit;
    // End of variables declaration//GEN-END:variables

}
