/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_assginment.InventoryManager;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivenn
 */
public class Supplier_Management_Interface extends javax.swing.JFrame {

    /**
     * Creates new form Supplier_Management_Interface
     */
    public Supplier_Management_Interface() {
        initComponents();
        displayAllSuppliers();
    }
    
    public void refreshSupplierTable() {
        DefaultTableModel model = (DefaultTableModel) tblSupplier.getModel();
        model.setRowCount(0); 

        for (Supplier supplier : Supplier.getAllSuppliers()) { 
            model.addRow(new Object[]{
            supplier.getSupplierId(),
            supplier.getSupplierName(),
            supplier.getContactNumber(),
            supplier.getEmail(),
            supplier.getItemIds(), 
            supplier.getPaymentMethod(),
            supplier.getShippingMethod(),
            supplier.getSupplyCapacity(),
            supplier.getLeadTime()
        });
        }
    }
    
    //Display all supplier in default
    private void displayAllSuppliers() {
        Supplier.loadSuppliersFromFile("src/User_data/suppliers.txt");
        refreshSupplierTable();
        DefaultTableModel model = (DefaultTableModel) tblSupplier.getModel();
        model.setRowCount(0); 
        
        //Add all suppliers to the table
        for (Supplier supplier : Supplier.allSuppliers) {
            model.addRow(new Object[]{
                supplier.getSupplierId(),
                supplier.getSupplierName(),
                supplier.getContactNumber(),
                supplier.getItemIds(),
                supplier.getPaymentMethod(),
                supplier.getShippingMethod(),
                supplier.getSupplyCapacity(),
                supplier.getLeadTime()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSearchSupplier = new javax.swing.JLabel();
        txtSearchSupplier = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        btnAddSupplier = new javax.swing.JButton();
        btnEditSupplier = new javax.swing.JButton();
        btnDeleteSupplier = new javax.swing.JButton();
        btnBackToMenuFromSupplier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        lblSearchSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSearchSupplier.setText("Search: ");

        txtSearchSupplier.setForeground(new java.awt.Color(153, 153, 153));
        txtSearchSupplier.setText("Enter supplier name or id");
        txtSearchSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchSupplierActionPerformed(evt);
            }
        });

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Supplier ID", "Supplier Name", "Contact Number", "Email", "Item IDs", "Payment Method", "Shipping Method", "Supply Capacity", "Lead Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSupplier);

        btnAddSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddSupplier.setText("Add");
        btnAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplierActionPerformed(evt);
            }
        });

        btnEditSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditSupplier.setText("Edit");
        btnEditSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSupplierActionPerformed(evt);
            }
        });

        btnDeleteSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteSupplier.setText("Delete");
        btnDeleteSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSupplierActionPerformed(evt);
            }
        });

        btnBackToMenuFromSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackToMenuFromSupplier.setText("Back to Menu");
        btnBackToMenuFromSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuFromSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblSearchSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(488, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnAddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnEditSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnDeleteSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackToMenuFromSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchSupplier)
                    .addComponent(txtSearchSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnEditSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBackToMenuFromSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchSupplierActionPerformed
        String searchText = txtSearchSupplier.getText().trim(); 
        boolean supplierFound = false; 
        DefaultTableModel model = (DefaultTableModel) tblSupplier.getModel();
        model.setRowCount(0); 

        //Find matching suppliers
        List<Supplier> suppliers = Supplier.searchSuppliers(searchText);

        for (Supplier supplier : suppliers) {
            model.addRow(new Object[]{
                supplier.getSupplierId(),
                supplier.getSupplierName(),
                supplier.getContactNumber(),
                supplier.getEmail(),
                String.join(", ", supplier.getItemIds()), // Assuming itemIds is a List, join them as a string
                supplier.getPaymentMethod(),
                supplier.getShippingMethod(),
                supplier.getSupplyCapacity(),
                supplier.getLeadTime()
            });
            supplierFound = true;
        }

        if (!supplierFound) {
            JOptionPane.showMessageDialog(null, "No supplier found with the input ID or Name.", "Supplier Not Found", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_txtSearchSupplierActionPerformed

    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        Add_New_Supplier addSupplier = new Add_New_Supplier(this);
        addSupplier.setVisible(true);
        refreshSupplierTable();
    }//GEN-LAST:event_btnAddSupplierActionPerformed

    private void btnEditSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSupplierActionPerformed
        int selectedRow = tblSupplier.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a supplier to edit!", "Selection Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String supplierId = tblSupplier.getValueAt(selectedRow, 0).toString();  
        String supplierName = tblSupplier.getValueAt(selectedRow, 1).toString();  
        String contactNumber = tblSupplier.getValueAt(selectedRow, 2).toString();  
        String email = tblSupplier.getValueAt(selectedRow, 3).toString();  
        String itemIdsStr = tblSupplier.getValueAt(selectedRow, 4).toString(); 
        List<String> itemIds = new ArrayList<>(Arrays.asList(itemIdsStr.split(","))); 
        String paymentMethod = tblSupplier.getValueAt(selectedRow, 5).toString();  
        String shippingMethod = tblSupplier.getValueAt(selectedRow, 6).toString();  
        String supplyCapacity = tblSupplier.getValueAt(selectedRow, 7).toString();  
        String leadTime = tblSupplier.getValueAt(selectedRow, 8).toString();  
        

        //Create a Supplier object for the selected supplier
        Supplier selectedSupplier = new Supplier(supplierId, supplierName, contactNumber, email, itemIds, paymentMethod, shippingMethod, supplyCapacity, leadTime);

        //Directed to edit supplier Interface
        Edit_Supplier editSupplier = new Edit_Supplier(selectedSupplier);
        editSupplier.setMainInterface(this);
        editSupplier.setVisible(true);

    }//GEN-LAST:event_btnEditSupplierActionPerformed

    private void btnBackToMenuFromSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuFromSupplierActionPerformed
        new Inventory_Interface().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToMenuFromSupplierActionPerformed

    private void btnDeleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSupplierActionPerformed
        int selectedRow = tblSupplier.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an supplier to delete!", "Selection Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Confirm deletion
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this supplier?",
                "Delete Confirmation",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            //Get the supplier ID from the selected row
            String supplierId = tblSupplier.getValueAt(selectedRow, 0).toString();

            //Delete the supplier
            boolean success = Supplier.deleteSupplierById(supplierId);

            if (success) {
                JOptionPane.showMessageDialog(this, "Supplier deleted successfully!", "Deletion Successful", JOptionPane.INFORMATION_MESSAGE);

                // Refresh the table data (you need to re-fetch data and update the table model)
                refreshSupplierTable();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete supplier. Please try again.", "Deletion Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteSupplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier_Management_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier_Management_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier_Management_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier_Management_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier_Management_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JButton btnBackToMenuFromSupplier;
    private javax.swing.JButton btnDeleteSupplier;
    private javax.swing.JButton btnEditSupplier;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearchSupplier;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtSearchSupplier;
    // End of variables declaration//GEN-END:variables
}
